-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.campaigns (
  campaign_id bigint NOT NULL DEFAULT nextval('campaigns_campaign_id_seq'::regclass),
  title text NOT NULL,
  description text,
  category text,
  goal numeric,
  deadline date,
  status text DEFAULT 'draft'::text,
  created_by bigint,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT campaigns_pkey PRIMARY KEY (campaign_id)
);
CREATE TABLE public.case_conferences (
  conference_id bigint NOT NULL DEFAULT nextval('case_conferences_conference_id_seq'::regclass),
  resident_id bigint NOT NULL,
  conference_date date NOT NULL,
  conference_type text,
  summary text,
  decisions_made text,
  next_steps text,
  next_conference_date date,
  created_by text,
  CONSTRAINT case_conferences_pkey PRIMARY KEY (conference_id),
  CONSTRAINT case_conferences_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(resident_id)
);
CREATE TABLE public.donation_allocations (
  allocation_id bigint NOT NULL,
  donation_id bigint,
  safehouse_id bigint,
  program_area text,
  amount_allocated numeric,
  allocation_date date,
  allocation_notes text,
  CONSTRAINT donation_allocations_pkey PRIMARY KEY (allocation_id),
  CONSTRAINT donation_allocations_donation_id_fkey FOREIGN KEY (donation_id) REFERENCES public.donations(donation_id),
  CONSTRAINT donation_allocations_safehouse_id_fkey FOREIGN KEY (safehouse_id) REFERENCES public.safehouses(safehouse_id)
);
CREATE TABLE public.donations (
  donation_id bigint NOT NULL,
  supporter_id bigint,
  donation_type text,
  donation_date date,
  is_recurring boolean,
  campaign_name text,
  channel_source text,
  currency_code text,
  amount numeric,
  estimated_value numeric,
  impact_unit text,
  notes text,
  referral_post_id bigint,
  campaign_id bigint,
  safehouse_id bigint,
  attributed_outcome_score double precision,
  attribution_run_id bigint,
  CONSTRAINT donations_pkey PRIMARY KEY (donation_id),
  CONSTRAINT donations_supporter_id_fkey FOREIGN KEY (supporter_id) REFERENCES public.supporters(supporter_id),
  CONSTRAINT donations_referral_post_id_fkey FOREIGN KEY (referral_post_id) REFERENCES public.social_media_posts(post_id),
  CONSTRAINT donations_safehouse_id_fkey FOREIGN KEY (safehouse_id) REFERENCES public.safehouses(safehouse_id),
  CONSTRAINT donations_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(campaign_id),
  CONSTRAINT donations_attribution_run_id_fkey FOREIGN KEY (attribution_run_id) REFERENCES public.ml_pipeline_runs(run_id)
);
CREATE TABLE public.donor_viewed_items (
  id bigint NOT NULL DEFAULT nextval('donor_viewed_items_id_seq'::regclass),
  supporter_id bigint,
  item_type text,
  item_id bigint,
  viewed_at timestamp without time zone DEFAULT now(),
  CONSTRAINT donor_viewed_items_pkey PRIMARY KEY (id),
  CONSTRAINT donor_viewed_items_supporter_id_fkey FOREIGN KEY (supporter_id) REFERENCES public.supporters(supporter_id)
);
CREATE TABLE public.education_records (
  education_record_id bigint NOT NULL,
  resident_id bigint,
  record_date date,
  education_level text,
  school_name text,
  enrollment_status text,
  attendance_rate numeric,
  progress_percent numeric,
  completion_status text,
  notes text,
  CONSTRAINT education_records_pkey PRIMARY KEY (education_record_id),
  CONSTRAINT education_records_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(resident_id)
);
CREATE TABLE public.health_wellbeing_records (
  health_record_id bigint NOT NULL,
  resident_id bigint,
  record_date date,
  general_health_score numeric,
  nutrition_score numeric,
  sleep_quality_score numeric,
  energy_level_score numeric,
  height_cm numeric,
  weight_kg numeric,
  bmi numeric,
  medical_checkup_done boolean,
  dental_checkup_done boolean,
  psychological_checkup_done boolean,
  notes text,
  CONSTRAINT health_wellbeing_records_pkey PRIMARY KEY (health_record_id),
  CONSTRAINT health_wellbeing_records_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(resident_id)
);
CREATE TABLE public.home_visitations (
  visitation_id bigint NOT NULL,
  resident_id bigint,
  visit_date date,
  social_worker text,
  visit_type text,
  location_visited text,
  family_members_present text,
  purpose text,
  observations text,
  family_cooperation_level text,
  safety_concerns_noted boolean,
  follow_up_needed boolean,
  follow_up_notes text,
  visit_outcome text,
  CONSTRAINT home_visitations_pkey PRIMARY KEY (visitation_id),
  CONSTRAINT home_visitations_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(resident_id)
);
CREATE TABLE public.in_kind_donation_items (
  item_id bigint NOT NULL,
  donation_id bigint,
  item_name text,
  item_category text,
  quantity numeric,
  unit_of_measure text,
  estimated_unit_value numeric,
  intended_use text,
  received_condition text,
  CONSTRAINT in_kind_donation_items_pkey PRIMARY KEY (item_id),
  CONSTRAINT in_kind_donation_items_donation_id_fkey FOREIGN KEY (donation_id) REFERENCES public.donations(donation_id)
);
CREATE TABLE public.incident_reports (
  incident_id bigint NOT NULL,
  resident_id bigint,
  safehouse_id bigint,
  incident_date date,
  incident_type text,
  severity text,
  description text,
  response_taken text,
  resolved boolean,
  resolution_date date,
  reported_by text,
  follow_up_required boolean,
  status text,
  CONSTRAINT incident_reports_pkey PRIMARY KEY (incident_id),
  CONSTRAINT incident_reports_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(resident_id),
  CONSTRAINT incident_reports_safehouse_id_fkey FOREIGN KEY (safehouse_id) REFERENCES public.safehouses(safehouse_id)
);
CREATE TABLE public.intervention_plans (
  plan_id bigint NOT NULL,
  resident_id bigint,
  plan_category text,
  plan_description text,
  services_provided text,
  target_value numeric,
  target_date date,
  status text,
  case_conference_date date,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  effectiveness_outcome_score double precision,
  effectiveness_band text,
  effectiveness_outcome_drivers jsonb,
  effectiveness_score_updated_at timestamp with time zone,
  CONSTRAINT intervention_plans_pkey PRIMARY KEY (plan_id),
  CONSTRAINT intervention_plans_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(resident_id)
);
CREATE TABLE public.ml_pipeline_runs (
  run_id bigint NOT NULL DEFAULT nextval('ml_pipeline_runs_run_id_seq'::regclass),
  pipeline_name text NOT NULL,
  display_name text,
  model_name text,
  status text NOT NULL DEFAULT 'completed'::text,
  trained_at timestamp with time zone NOT NULL DEFAULT now(),
  data_source text,
  source_commit text,
  metrics_json jsonb,
  manifest_json jsonb,
  scored_entity_count integer,
  feature_importance_json jsonb,
  CONSTRAINT ml_pipeline_runs_pkey PRIMARY KEY (run_id)
);
CREATE TABLE public.ml_prediction_snapshots (
  prediction_id bigint NOT NULL DEFAULT nextval('ml_prediction_snapshots_prediction_id_seq'::regclass),
  run_id bigint NOT NULL,
  pipeline_name text NOT NULL,
  entity_type text NOT NULL,
  entity_id bigint,
  entity_key text NOT NULL,
  entity_label text,
  safehouse_id bigint,
  record_timestamp timestamp with time zone,
  prediction_value integer,
  prediction_score double precision NOT NULL,
  rank_order integer NOT NULL,
  context_json jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  band_label text,
  action_code text,
  CONSTRAINT ml_prediction_snapshots_pkey PRIMARY KEY (prediction_id),
  CONSTRAINT ml_prediction_snapshots_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.ml_pipeline_runs(run_id)
);
CREATE TABLE public.partner_assignments (
  assignment_id bigint NOT NULL,
  partner_id bigint,
  safehouse_id bigint,
  program_area text,
  assignment_start date,
  assignment_end date,
  responsibility_notes text,
  is_primary boolean,
  status text,
  CONSTRAINT partner_assignments_pkey PRIMARY KEY (assignment_id),
  CONSTRAINT partner_assignments_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(partner_id),
  CONSTRAINT partner_assignments_safehouse_id_fkey FOREIGN KEY (safehouse_id) REFERENCES public.safehouses(safehouse_id)
);
CREATE TABLE public.partners (
  partner_id bigint NOT NULL,
  partner_name text,
  partner_type text,
  role_type text,
  contact_name text,
  email text,
  phone text,
  region text,
  status text,
  start_date date,
  end_date date,
  notes text,
  CONSTRAINT partners_pkey PRIMARY KEY (partner_id)
);
CREATE TABLE public.process_recordings (
  recording_id bigint NOT NULL,
  resident_id bigint,
  session_date date,
  social_worker text,
  session_type text,
  session_duration_minutes integer,
  emotional_state_observed text,
  emotional_state_end text,
  session_narrative text,
  interventions_applied text,
  follow_up_actions text,
  progress_noted boolean,
  concerns_flagged boolean,
  referral_made boolean,
  notes_restricted text,
  CONSTRAINT process_recordings_pkey PRIMARY KEY (recording_id),
  CONSTRAINT process_recordings_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(resident_id)
);
CREATE TABLE public.program_updates (
  update_id bigint NOT NULL DEFAULT nextval('program_updates_update_id_seq'::regclass),
  title text NOT NULL,
  summary text,
  category text,
  is_published boolean DEFAULT false,
  published_at timestamp without time zone,
  created_by bigint,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT program_updates_pkey PRIMARY KEY (update_id)
);
CREATE TABLE public.public_impact_snapshots (
  snapshot_id bigint NOT NULL,
  snapshot_date date,
  headline text,
  summary_text text,
  metric_payload_json jsonb,
  is_published boolean,
  published_at timestamp without time zone,
  projected_gap_php_30d numeric,
  funding_gap_band text,
  funding_gap_updated_at timestamp with time zone,
  CONSTRAINT public_impact_snapshots_pkey PRIMARY KEY (snapshot_id)
);
CREATE TABLE public.residents (
  resident_id bigint NOT NULL,
  case_control_no text,
  internal_code text,
  safehouse_id bigint,
  case_status text,
  sex text,
  date_of_birth date,
  birth_status text,
  place_of_birth text,
  religion text,
  case_category text,
  sub_cat_orphaned boolean,
  sub_cat_trafficked boolean,
  sub_cat_child_labor boolean,
  sub_cat_physical_abuse boolean,
  sub_cat_sexual_abuse boolean,
  sub_cat_osaec boolean,
  sub_cat_cicl boolean,
  sub_cat_at_risk boolean,
  sub_cat_street_child boolean,
  sub_cat_child_with_hiv boolean,
  is_pwd boolean,
  pwd_type text,
  has_special_needs boolean,
  special_needs_diagnosis text,
  family_is_4ps boolean,
  family_solo_parent boolean,
  family_indigenous boolean,
  family_parent_pwd boolean,
  family_informal_settler boolean,
  date_of_admission date,
  age_upon_admission text,
  present_age text,
  length_of_stay text,
  referral_source text,
  referring_agency_person text,
  date_colb_registered date,
  date_colb_obtained date,
  assigned_social_worker text,
  initial_case_assessment text,
  date_case_study_prepared date,
  reintegration_type text,
  reintegration_status text,
  initial_risk_level text,
  current_risk_level text,
  date_enrolled date,
  date_closed date,
  created_at timestamp without time zone,
  notes_restricted text,
  regression_risk_score double precision,
  regression_risk_band text,
  regression_risk_drivers jsonb,
  regression_recommended_action text,
  regression_score_updated_at timestamp with time zone,
  reintegration_readiness_score double precision,
  reintegration_readiness_band text,
  reintegration_readiness_drivers jsonb,
  reintegration_recommended_action text,
  reintegration_score_updated_at timestamp with time zone,
  ml_scores_restricted boolean,
  CONSTRAINT residents_pkey PRIMARY KEY (resident_id),
  CONSTRAINT residents_safehouse_id_fkey FOREIGN KEY (safehouse_id) REFERENCES public.safehouses(safehouse_id)
);
CREATE TABLE public.safehouse_monthly_metrics (
  metric_id bigint NOT NULL,
  safehouse_id bigint,
  month_start date,
  month_end date,
  active_residents integer,
  avg_education_progress numeric,
  avg_health_score numeric,
  process_recording_count integer,
  home_visitation_count integer,
  incident_count integer,
  notes text,
  composite_health_score double precision,
  peer_rank integer,
  health_band text,
  trend_direction text,
  health_score_drivers jsonb,
  incident_severity_distribution jsonb,
  health_score_computed_at timestamp with time zone,
  health_score_run_id bigint,
  CONSTRAINT safehouse_monthly_metrics_pkey PRIMARY KEY (metric_id),
  CONSTRAINT safehouse_monthly_metrics_safehouse_id_fkey FOREIGN KEY (safehouse_id) REFERENCES public.safehouses(safehouse_id),
  CONSTRAINT safehouse_monthly_metrics_health_score_run_id_fkey FOREIGN KEY (health_score_run_id) REFERENCES public.ml_pipeline_runs(run_id)
);
CREATE TABLE public.safehouses (
  safehouse_id bigint NOT NULL,
  safehouse_code text,
  name text,
  region text,
  city text,
  province text,
  country text,
  open_date date,
  status text,
  capacity_girls integer,
  capacity_staff integer,
  current_occupancy integer,
  notes text,
  CONSTRAINT safehouses_pkey PRIMARY KEY (safehouse_id)
);
CREATE TABLE public.social_media_posts (
  post_id bigint NOT NULL,
  platform text,
  platform_post_id text,
  post_url text,
  created_at timestamp without time zone,
  day_of_week text,
  post_hour integer,
  post_type text,
  media_type text,
  caption text,
  hashtags text,
  num_hashtags integer,
  mentions_count integer,
  has_call_to_action boolean,
  call_to_action_type text,
  content_topic text,
  sentiment_tone text,
  caption_length integer,
  features_resident_story boolean,
  campaign_name text,
  is_boosted boolean,
  boost_budget_php numeric,
  impressions integer,
  reach integer,
  likes integer,
  comments integer,
  shares integer,
  saves integer,
  click_throughs integer,
  video_views numeric,
  engagement_rate numeric,
  profile_visits integer,
  donation_referrals integer,
  estimated_donation_value_php numeric,
  follower_count_at_post integer,
  watch_time_seconds numeric,
  avg_view_duration_seconds numeric,
  subscriber_count_at_post numeric,
  forwards numeric,
  conversion_prediction_score double precision,
  predicted_referral_count numeric,
  predicted_donation_value_php numeric,
  conversion_band text,
  conversion_top_drivers jsonb,
  conversion_comparable_post_ids jsonb,
  conversion_score_updated_at timestamp with time zone,
  CONSTRAINT social_media_posts_pkey PRIMARY KEY (post_id)
);
CREATE TABLE public.staff_safehouse_assignments (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  user_id character varying NOT NULL,
  safehouse_id bigint NOT NULL,
  CONSTRAINT staff_safehouse_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT staff_safehouse_assignments_safehouse_id_fkey FOREIGN KEY (safehouse_id) REFERENCES public.safehouses(safehouse_id)
);
CREATE TABLE public.supporters (
  supporter_id bigint NOT NULL,
  supporter_type text,
  display_name text,
  organization_name text,
  first_name text,
  last_name text,
  relationship_type text,
  region text,
  country text,
  email text,
  phone text,
  status text,
  created_at text,
  first_donation_date date,
  acquisition_channel text,
  identity_user_id character varying,
  can_login boolean NOT NULL DEFAULT false,
  recurring_enabled boolean NOT NULL DEFAULT false,
  churn_risk_score double precision,
  churn_band text,
  churn_top_drivers jsonb,
  churn_recommended_action text,
  churn_score_updated_at timestamp with time zone,
  upgrade_likelihood_score double precision,
  upgrade_band text,
  upgrade_top_drivers jsonb,
  upgrade_recommended_ask_band text,
  upgrade_score_updated_at timestamp with time zone,
  CONSTRAINT supporters_pkey PRIMARY KEY (supporter_id)
);
CREATE TABLE public.users (
  id integer NOT NULL DEFAULT nextval('users_id_seq'::regclass),
  username text NOT NULL UNIQUE,
  email text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  role text NOT NULL DEFAULT 'public'::text CHECK (role = ANY (ARRAY['public'::text, 'donor'::text, 'staff'::text, 'admin'::text, 'super_admin'::text])),
  is_active boolean NOT NULL DEFAULT true,
  mfa_enabled boolean NOT NULL DEFAULT false,
  last_login timestamp with time zone,
  supporter_id bigint,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_supporter_id_fkey FOREIGN KEY (supporter_id) REFERENCES public.supporters(supporter_id)
);