import { pgTable, text, bigserial, bigint, date, boolean, timestamp, doublePrecision, jsonb } from "drizzle-orm/pg-core";
import { safehousesTable } from "./safehouses";

export const residentsTable = pgTable("residents", {
  residentId:                     bigserial("resident_id", { mode: "number" }).primaryKey(),
  caseControlNo:                  text("case_control_no"),
  internalCode:                   text("internal_code"),
  safehouseId:                    bigint("safehouse_id", { mode: "number" }).references(() => safehousesTable.safehouseId),
  caseStatus:                     text("case_status"),
  sex:                            text("sex"),
  dateOfBirth:                    date("date_of_birth"),
  birthStatus:                    text("birth_status"),
  placeOfBirth:                   text("place_of_birth"),
  religion:                       text("religion"),
  caseCategory:                   text("case_category"),
  subCatOrphaned:                 boolean("sub_cat_orphaned"),
  subCatTrafficked:               boolean("sub_cat_trafficked"),
  subCatChildLabor:               boolean("sub_cat_child_labor"),
  subCatPhysicalAbuse:            boolean("sub_cat_physical_abuse"),
  subCatSexualAbuse:              boolean("sub_cat_sexual_abuse"),
  subCatOsaec:                    boolean("sub_cat_osaec"),
  subCatCicl:                     boolean("sub_cat_cicl"),
  subCatAtRisk:                   boolean("sub_cat_at_risk"),
  subCatStreetChild:              boolean("sub_cat_street_child"),
  subCatChildWithHiv:             boolean("sub_cat_child_with_hiv"),
  isPwd:                          boolean("is_pwd"),
  pwdType:                        text("pwd_type"),
  hasSpecialNeeds:                boolean("has_special_needs"),
  specialNeedsDiagnosis:          text("special_needs_diagnosis"),
  familyIs4ps:                    boolean("family_is_4ps"),
  familySoloParent:               boolean("family_solo_parent"),
  familyIndigenous:               boolean("family_indigenous"),
  familyParentPwd:                boolean("family_parent_pwd"),
  familyInformalSettler:          boolean("family_informal_settler"),
  dateOfAdmission:                date("date_of_admission"),
  ageUponAdmission:               text("age_upon_admission"),
  presentAge:                     text("present_age"),
  lengthOfStay:                   text("length_of_stay"),
  referralSource:                 text("referral_source"),
  referringAgencyPerson:          text("referring_agency_person"),
  dateColbRegistered:             date("date_colb_registered"),
  dateColbObtained:               date("date_colb_obtained"),
  assignedSocialWorker:           text("assigned_social_worker"),
  initialCaseAssessment:          text("initial_case_assessment"),
  dateCaseStudyPrepared:          date("date_case_study_prepared"),
  reintegrationType:              text("reintegration_type"),
  reintegrationStatus:            text("reintegration_status"),
  initialRiskLevel:               text("initial_risk_level"),
  currentRiskLevel:               text("current_risk_level"),
  dateEnrolled:                   date("date_enrolled"),
  dateClosed:                     date("date_closed"),
  createdAt:                      timestamp("created_at"),
  notesRestricted:                text("notes_restricted"),
  regressionRiskScore:            doublePrecision("regression_risk_score"),
  regressionRiskBand:             text("regression_risk_band"),
  regressionRiskDrivers:          jsonb("regression_risk_drivers"),
  regressionRecommendedAction:    text("regression_recommended_action"),
  regressionScoreUpdatedAt:       timestamp("regression_score_updated_at", { withTimezone: true }),
  reintegrationReadinessScore:    doublePrecision("reintegration_readiness_score"),
  reintegrationReadinessBand:     text("reintegration_readiness_band"),
  reintegrationReadinessDrivers:  jsonb("reintegration_readiness_drivers"),
  reintegrationRecommendedAction: text("reintegration_recommended_action"),
  reintegrationScoreUpdatedAt:    timestamp("reintegration_score_updated_at", { withTimezone: true }),
  mlScoresRestricted:             boolean("ml_scores_restricted"),
});

export type Resident = typeof residentsTable.$inferSelect;
export type InsertResident = typeof residentsTable.$inferInsert;
