import { pgTable, text, bigserial, integer, numeric, boolean, timestamp, doublePrecision, jsonb } from "drizzle-orm/pg-core";

export const socialMediaPostsTable = pgTable("social_media_posts", {
  postId:                       bigserial("post_id", { mode: "number" }).primaryKey(),
  platform:                     text("platform"),
  platformPostId:               text("platform_post_id"),
  postUrl:                      text("post_url"),
  createdAt:                    timestamp("created_at"),
  dayOfWeek:                    text("day_of_week"),
  postHour:                     integer("post_hour"),
  postType:                     text("post_type"),
  mediaType:                    text("media_type"),
  caption:                      text("caption"),
  hashtags:                     text("hashtags"),
  numHashtags:                  integer("num_hashtags"),
  mentionsCount:                integer("mentions_count"),
  hasCallToAction:              boolean("has_call_to_action"),
  callToActionType:             text("call_to_action_type"),
  contentTopic:                 text("content_topic"),
  sentimentTone:                text("sentiment_tone"),
  captionLength:                integer("caption_length"),
  featuresResidentStory:        boolean("features_resident_story"),
  campaignName:                 text("campaign_name"),
  isBoosted:                    boolean("is_boosted"),
  boostBudgetPhp:               numeric("boost_budget_php"),
  impressions:                  integer("impressions"),
  reach:                        integer("reach"),
  likes:                        integer("likes"),
  comments:                     integer("comments"),
  shares:                       integer("shares"),
  saves:                        integer("saves"),
  clickThroughs:                integer("click_throughs"),
  videoViews:                   numeric("video_views"),
  engagementRate:               numeric("engagement_rate"),
  profileVisits:                integer("profile_visits"),
  donationReferrals:            integer("donation_referrals"),
  estimatedDonationValuePhp:    numeric("estimated_donation_value_php"),
  followerCountAtPost:          integer("follower_count_at_post"),
  watchTimeSeconds:             numeric("watch_time_seconds"),
  avgViewDurationSeconds:       numeric("avg_view_duration_seconds"),
  subscriberCountAtPost:        numeric("subscriber_count_at_post"),
  forwards:                     numeric("forwards"),
  conversionPredictionScore:    doublePrecision("conversion_prediction_score"),
  predictedReferralCount:       numeric("predicted_referral_count"),
  predictedDonationValuePhp:    numeric("predicted_donation_value_php"),
  conversionBand:               text("conversion_band"),
  conversionTopDrivers:         jsonb("conversion_top_drivers"),
  conversionComparablePostIds:  jsonb("conversion_comparable_post_ids"),
  conversionScoreUpdatedAt:     timestamp("conversion_score_updated_at", { withTimezone: true }),
});

export type SocialMediaPost = typeof socialMediaPostsTable.$inferSelect;
export type InsertSocialMediaPost = typeof socialMediaPostsTable.$inferInsert;
