using System.Text.Json;

namespace backend.intex.DTOs.Supporters;

public sealed record SupporterResponseDto(
    long SupporterId,
    long Id,
    string? SupporterType,
    string? SupportType,
    string? DisplayName,
    string? OrganizationName,
    string? Organization,
    string? FirstName,
    string? LastName,
    string? RelationshipType,
    string? Region,
    string? Country,
    string? Email,
    string? Phone,
    string? Status,
    string? CreatedAt,
    string? FirstDonationDate,
    string? DonorSince,
    string? AcquisitionChannel,
    string? IdentityUserId,
    bool CanLogin,
    bool RecurringEnabled,
    bool IsRecurring,
    double? ChurnRiskScore,
    string? ChurnBand,
    JsonDocument? ChurnTopDrivers,
    string? ChurnRecommendedAction,
    string? ChurnScoreUpdatedAt,
    double? UpgradeLikelihoodScore,
    string? UpgradeBand,
    JsonDocument? UpgradeTopDrivers,
    string? UpgradeRecommendedAskBand,
    string? UpgradeScoreUpdatedAt,
    decimal? LifetimeGiving,
    int? DonationCount,
    string? LastGiftDate,
    decimal? LastGiftAmount,
    bool? HasRecurring,
    string? CommunicationPreference,
    string? DonorTier
);
